name: Release database export

on:
  schedule:
    # Run every day at midnight (00:00 UTC)
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  actions: write # Permission to delete old workflow runs
  contents: write # Permission to create releases

jobs:
  export_database:
    runs-on: ubuntu-latest
    steps:
      - name: Download data
        env:
          API_KEY: ${{ secrets.DATABASE_EXPORT_API_KEY }}
        run: |
          curl --fail -H "API_KEY: $API_KEY" -o basegame-data.zip https://ingest.mapsnotincluded.org/export/basegame
          curl --fail -H "API_KEY: $API_KEY" -o spacedout-data.zip https://ingest.mapsnotincluded.org/export/spacedout
          curl --fail -H "API_KEY: $API_KEY" -o spacedout-classic-data.zip https://ingest.mapsnotincluded.org/export/spacedout-classic
          curl --fail -H "API_KEY: $API_KEY" -o frostyplanet-data.zip https://ingest.mapsnotincluded.org/export/frostyplanet
      - name: set NOW
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "data-${{ env.NOW }}"
          release_name: "Data ${{ env.NOW }} "
          body: "Automated export of collected seed data in JSON format."
          draft: false
          prerelease: false
      # Basegame
      - name: Upload basegame-data.zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./basegame-data.zip
          asset_name: basegame-data-${{ env.NOW }}.zip
          asset_content_type: application/zip
      # Spaced Out
      - name: Upload spacedout-data.zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./spacedout-data.zip
          asset_name: spacedout-data-${{ env.NOW }}.zip
          asset_content_type: application/zip
      # Spaced Out Classic
      - name: Upload spacedout-classic-data.zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./spacedout-classic-data.zip
          asset_name: spacedout-classic-data-${{ env.NOW }}.zip
          asset_content_type: application/zip
      # Frosty Planet
      - name: Upload frostyplanet-data.zip to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./frostyplanet-data.zip
          asset_name: frostyplanet-data-${{ env.NOW }}.zip
          asset_content_type: application/zip
      # Clean up
      - name: Delete old releases
        uses: dev-drprasad/delete-older-releases@v0.3.4
        with:
          keep_latest: 1
          delete_tag_pattern: data-*
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
